
---
# Pod1
apiVersion: v1
kind:       Pod
metadata:
  name: iconoflix1
  labels:
    app: iconoflix
spec:
  containers:
  - name:  iconoflix
    image: quay.io/imhotepio/iconoflix:mem
    ports:
    - name:          api
      containerPort: 4000
---
# Pod2
apiVersion: v1
kind:       Pod
metadata:
  name: iconoflix2
  labels:
    app: iconoflix
spec:
  containers:
  - name:  iconoflix
    image: quay.io/imhotepio/iconoflix:mem
    ports:
    - name:          api
      containerPort: 4000
---
# Service
kind: Service
apiVersion: v1
metadata:
  name: <!!CHANGE_ME!!>
spec:
  type:  <!!CHANGE_ME!!>
  <!!CHANGE_ME!!>
  ports:
    - name:       <!!CHANGE_ME!!>
      port:       <!!CHANGE_ME!!>
      targetPort: <!!CHANGE_ME!!>
      <!!CHANGE_ME!!>
