---
# Pod1
apiVersion: v1
kind: Pod
metadata:
  name: !!!CHANGE_ME!!!
  labels:
    app: iconoflix
spec:
  containers:
    - name: iconoflix
      image: !!!CHANGE_ME!!!
      ports:
        - name: api
          containerPort: !!!CHANGE_ME!!!
