apiVersion: apps/v1
kind: Deployment
metadata:
  name: <!!CHANGE_ME!!>
spec:
  replicas: <!!CHANGE_ME!!>
  selector: <!!CHANGE_ME!!>
  template:
    metadata:
      labels:
        app: <!!CHANGE_ME!!>
    spec:
      containers:
        - name: iconoflix
          image: <!!CHANGE_ME!!>
          ports:
            - containerPort: <!!CHANGE_ME!!>
