apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updater
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: update
              image: <!!CHANGE_ME!!>
              command: <!!CHANGE_ME!!>
              args: <!!CHANGE_ME!!>
