apiVersion: v1
kind:       Service
metadata:
  name: hangmanservice
spec:
  selector:
    app: hangmanapp
  type: NodePort
  ports:
    - name:       http
      protocol:   TCP  
      port:       5000
      nodePort: 30400
